notifications:
  email: false

env:
  global:
    - BUILD_DEPENDS="cvxopt"
    - TEST_DEPENDS="pytest pytest-cov coveralls"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '2.7'
      env: CHOMPACK_LAPACK_LIB=blas
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: '3.6'
      env: CHOMPACK_LAPACK_LIB=blas
    - os: osx
      language: python
      env: PYVERSION=2.7
        CHOMPACK_BLAS_LIB_DIR=/usr/local/opt/openblas/lib
        CHOMPACK_BLAS_LIB=openblas CHOMPACK_LAPACK_LIB=openblas
      language: generic
    - os: osx
      language: python
      env: PYVERSION=3.6
        CHOMPACK_BLAS_LIB_DIR=/usr/local/opt/openblas/lib
        CHOMPACK_BLAS_LIB=openblas CHOMPACK_LAPACK_LIB=openblas
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-dev libopenblas-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall oclint; brew install openblas; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;bash miniconda.sh -b -p $HOME/miniconda; export PATH="$HOME/miniconda/bin:$PATH" ;  fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda create -y -n myenv python=$PYVERSION && source $HOME/miniconda/bin/activate myenv; fi
  - pip install $BUILD_DEPENDS

install:
  - python setup.py install

script:
  - pip install $TEST_DEPENDS
  - pytest --cov=chompack tests/

after_success:
  - coveralls
