name: macOS build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    env:
      CFLAGS: -target arm64-apple-macos15.0
      CVXOPT_BLAS_LIB_DIR: /usr/lib
      CVXOPT_BLAS_LIB: blas
      CVXOPT_LAPACK_LIB: lapack

    strategy:
      matrix:
        python-version: ['3.14']

    steps:
    - name: Checkout source    
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools setuptools_scm build wheel pytest pytest-cov coveralls

    - name: Build/install CHOMPACK
      run: |
        python -m build --wheel
        python -m pip install --find-links=${{github.workspace}}/dist chompack

    - name: Test with pytest
      run: |
        pytest --cov=chompack tests
